#!/bin/bash

# Use image label to cleanup possible orphaned images.
oImgs=$(buildah images | grep -F '<none>' | awk '{print $3}')
for img in $oImgs ; do
    if buildah inspect $img | grep -q '"AUTOMATION_CONTAINER_IMAGE": "ui-backend"'; then
        buildah rmi --force $img
    fi
done

if [ "$1" == "purge" ]; then
    if podman volume ls | awk '{print $2}' | grep ^ui-backend$; then
        printf "\n* Clean up uib volume...\n"
        podman volume rm ui-backend
        podman volume rm ui-backend-db
    fi
fi

# Force debconf cleanup.
echo PURGE | debconf-communicate automation-interface-ui-backend-container

exit 0
