#!/bin/bash

printf "\n* Container prerm...\n"
printf "\n* Cleanup...\n"

if podman ps | awk '{print $2}' | grep -E '\blocalhost/ui-backend(:|\b)'; then
    podman stop ui-backend
fi

if podman images | awk '{print $1}' | grep -q ^localhost/ui-backend$; then
    buildah rmi --force ui-backend
fi

# Be sure there is not rubbish around.
if podman ps --all | awk '{print $2}' | grep -E '\blocalhost/ui-backend(:|\b)'; then
    cIds=$( podman ps --all | awk '$2 ~ /^localhost\/ui-backend/ { print $1 }' )
    for id in $cIds; do
        podman rm -f $id
    done
fi

exit 0
